### PR TITLE
Fixed the blocked texts on the about page

### PR DESCRIPTION
**Pull request by EasyVector**
Dear developer:

Hello! I am the creator of issue #42, and I have fixed the blocked texts on the about page. After some tests, I think the code works well now. I would genuinely appreciate it if you could kindly revise my code and leave me some advice. Thank you so much for your precious time!

Here are the screenshots after my changes:

in the largest font and display:
copy

in the largest font and the smallest display:
copy

Thanks again! Blessings on your day! :)

### CODE REVIEW

**Comment by franklinbill** [comment]
I meet the same issue and agree with your fix. @yuhuitech

**Comment by pserwylo** [comment]
Thank you so much for your contribution @yuhuitech (and also @franklinbill for confirming and providing a review).

A couple of small bits of feedback about the contribution (though it is very good!):
* I have proposed another commit on top and will merge that (including your commit) in #44. That runs the Android Studio code formatter over the layout file to tidy things up (always a good idea before committing). It also removes the `FrameLayout` which wraps the `ConstraintLayout` inside the `ScrollView`. This isn't required, the `ScrollView` just requires one child, and the `ConstraintLayout` works fine for this. 
* I love the screenshots and the detail in this PR. Only recommendation regarding it is that you may wish to use a branch other than `master` in the future for fixes. For example, calling it `fix-42-large-font` or something like that will provide more context for both yourself and I.

Thank you very much for your contribution! I'm going to close this PR in favour of #44 which also includes this commit and one other, so thank you for that.

**Comment by EasyVector** [comment]
OK! Thank you so much for your advice on naming a branch. I totally understand this. :)

The reason why I used FrameLayout is to make sure all the margin settings work. During my testing, when I used ConstraintLayout, because the margin-top of the icon is so big that the bottom texts are still blocked even when Scrollview is used, and plus I did not want to change any original margin setting. So I used FrameLayout to guarantee that. 

That is my thought. You could refer to this: https://stackoverflow.com/questions/45306372/linearlayout-is-getting-cut-off-inside-scrollview-android/45306799#45306799 

Though it is about LinearLayout, they are much the same.

**Comment by pserwylo** [comment]
Ah I understand, thanks for the clarification. i guess that would be an additional piece of feedback. If you look at my code, I tend not to comment excesively. i used to teach programming at University and I hated when the marking guide took marks off for not commenting every method - it lead to really poor quality comments. I always encouraged my students to comment only when they needed to explain something non-obvious to others - this would be a great example (a link to the SO post, and the  description you have here).

Nevertheless, I think it seems to work well with just the `ConstraintLayout` in my testing. If I had two guess, I'd think two reasons - `ConstraintLayout` is much more modern than many other layouts, and they removed a lot of quirks that were present in other layouts, and also we mainly use padding instead of margin. If this is anything like CSS, padding is considered part of the size of the widget whereas margin is not.

Thanks again!

**Comment by EasyVector** [comment]
Thank you so much! You must be a wonderful teacher. Maybe I did not explain my intention very clearly at first but I tried to explain in the end. And thank you for telling me the information about CSS, I guess the margin in CSS is very similar to the one in Android XML layout files. And I agree with you about your opinion on `ConstraintLayout`, it is much more modern.

Also, I would like to say that how to change the UI of an app is not so easy because we not only have to make every component on the screen work in the right and more legible way, but also have to follow the opinions of developers. I think this is a very profound conversation. I am so glad we could talk about this!!

Thanks again!! Wish you have a nice day!

:)

**Pull request closed without merging**
